version: '3.8'


services:
  lb:
    image: haproxy:2.2
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  ws1:
    image: wsapp
    depends_on:
      - rds
    environment:
      - APPID=1111
  ws2:
    image: wsapp
    depends_on:
      - rds
    environment:
      - APPID=2222
  ws3:
    image: wsapp
    depends_on:
      - rds
    environment:
      - APPID=3333
  ws4:
    image: wsapp
    depends_on:
      - rds
    environment:
      - APPID=4444
  rds:
    image: redis
    ports:
      - "6379:6379"